### ISSUE TITLE
CSS types incorrectly extracted as `value`

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#1130]
The CSS type `<basic-shape>` is unexpectedly extracted with `value` as its `type` from [CSS Shapes 1](https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-shapes.json#L24-L29) and [CSS Shapes 2](https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-shapes-2.json#L30-L35), namespaced to the property `shape-inside`.

https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-shapes.json#L24-L29

It is also extracted as a type from [CSS Shape 1](https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-shapes.json#L93), as expected.

The problem also occurs for `<url>` namespaced to `shape-inside` in CSS Shapes 2, and for `<feature-tag-value>`. It might be non-exhaustive.

**Comment by tidoust** [comment]
That is "by design" in CSS specs and what I noted in #1117:

> Some of the extracts contain things that may look weird at first, but that's because the spec itself is weird. For instance, [CSS Will change](https://drafts.csswg.org/css-will-change-1/) defines a [`<custom-ident>`](https://drafts.csswg.org/css-will-change-1/#valdef-will-change-custom-ident) `value` construct whose actual value is the `<custom-ident>` `type` construct defined in CSS Values. Having both a namespaced `value` and a non-namespaced `<type>` is somewhat common in CSS specs.

The [namespaced `<basic-shape>` `value` definition](https://drafts.csswg.org/css-shapes/#valdef-shape-outside-basic-shape) is used in the spec to describe the meaning of the value in the context of a `shape-outside` property. It references the [non-namespaced `<basic-shape>` `type` definition](https://drafts.csswg.org/css-shapes/#typedef-basic-shape).

In the extract, the namespaced `<basic-shape>` `value` definition is under the `values` property of the object that describes the `shape-outside` CSS property. The non-namespaced `type` definition is under the root `values` property. There should never be a `value` type under the root `values` property (all `value` types are for something).
