### ISSUE TITLE
CSS `font-style` and `<grid-line>` are defined with invalid `values`

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#1133]
It seems that [`font-style`](https://github.com/w3c/webref/blob/ae9feb35a2d8040ed75efffb9e975bcb71cfacf3/ed/css/css-fonts.json#L138) and [`<grid-line>`](https://github.com/w3c/webref/blob/ae9feb35a2d8040ed75efffb9e975bcb71cfacf3/ed/css/css-grid.json#L336) include invalid `values`:

```json
{
  "name": "oblique <angle [−90deg,90deg]>?",
  "prose": "...",
  "type": "value",
  "value": "oblique <angle [-90deg,90deg]>?"
}
```

```json
{
  "name": "[ <integer [−∞,−1]> | <integer [1,∞]> ] && <custom-ident>?",
  "prose": "...",
  "type": "value",
  "value": "[ <integer [-∞,-1]> | <integer [1,∞]> ] && <custom-ident>?"
}
```

Aside: does the warning added [here](https://github.com/w3c/reffy/blob/fdd6ac7f505af598b36473b381a6ee38272bc6da/src/browserlib/extract-cssdfn.mjs#L186) is reported to me as a `webref` consumer? I think it would report `<extent-keyword>`, which was extracted in `reffy@v10` but is not anymore in `reffy@v11`, but I cannot run Reffy on my virtual dev env (Pupetter does not find Chrome).

**Comment by tidoust** [comment]
> It seems that [`font-style`](https://github.com/w3c/webref/blob/ae9feb35a2d8040ed75efffb9e975bcb71cfacf3/ed/css/css-fonts.json#L138) and [`<grid-line>`](https://github.com/w3c/webref/blob/ae9feb35a2d8040ed75efffb9e975bcb71cfacf3/ed/css/css-grid.json#L336) include invalid values

Is the `value` property invalid or is the `name` property invalid?

The `name` property is extracted as defined in the spec. The `value` property is normalized (and fixed). The `value` property should be valid CSS syntax. The `name` may not be but the `name` is not intended to be parsed in any way, it's just a name.

The underlying specs typically uses `−` instead of `-` in the text, so you'll find the larger version in the `name` property. The `value` property uses the regular minus character.

I hesitated and am still hesitating on what the extract should contain. It makes sense to stick to the name that the spec defines, e.g. to be able to relate that entry with the `dfns` extract also produced by Webref, which does not include any sort of normalization logic. At the same time, if you're parsing the `value` property of the parent property and trying to map items in `values` to the tokens it contains, it would be better to normalize the `name` as well.

(I'll look into `<extent-keyword>`. Not sure yet what happens here)

**Comment by cdoublev** [comment]
I was reporting an invalid `name`, yeah. 

It is a name for a part of the `<grid-line>` production that is further defined (with `<dfn>`) in a `<dl>`. It is not a function or a type. Maybe we could argue that it is a value. I totally see how someone may find these definitions usefull, and I can find a workaround to skip them.

I created this issue yesterday, I managed to run Puppeteer (but it was useless because I cannot debug the extractor), and I now have a better understanding of how CSS types/functions/values are extracted. It seems that `<extent-keyword>` is namespaced to `radial-gradient()`, which is not the deepest type.

**Comment by cdoublev** [comment]
Did you spot the typo [here](https://github.com/w3c/reffy/blob/fdd6ac7f505af598b36473b381a6ee38272bc6da/src/browserlib/extract-cssdfn.mjs#L249)?

```diff
- ?.find(p => checkChild(ancestor, p));
+ ?.find(p => checkChild(p));
```

This change seems to do the trick.

**Comment by tidoust** [comment]
Indeed, I was about to report that this was the root of the bug. That makes the code filter out a number of value constructs. I'll fix that. Thanks for the investigation and refactoring suggestion!

**Comment by cdoublev** [comment]
Closing as invalid.
