### ISSUE TITLE
CSS `<source-size-*>` are no longer extracted from HTML spec

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#1134]
Release notes of Webref v6 says that Reffy *no longer extracts re-definitions of selectors from the HTML spec (on purpose)*.

Explicitly, this means that [`<source-size-*>`](https://html.spec.whatwg.org/multipage/images.html#sizes-attributes) are [no longer extracted](https://github.com/w3c/webref/blob/%40webref/css%405.4.4/ed/css/html.json), but I cannot find their definitions in any other CSS spec.

Statically defining these three types on my side is not a problem, but I just wanted to clarify the reason why they are not extracted anymore.

**Comment by tidoust** [comment]
That is unrelated. These constructs are not selectors. They are no longer extracted because the spec fails to specify their type (no `data-dfn-type` attribute) and the extraction logic now relies on that type.

Ideally, the definitions should be completed with `data-dfn-type="type"` attributes, not to confuse them with "regular" terms and so that crawlers such as Reffy may understand that they are looking at CSS type definitions. Would you be up for a PR against the HTML spec?

**Comment by cdoublev** [comment]
Oh ok. I can submit a PR, of course. 

Aside: I was looking in the Bikeshed doc if it would also require `data-dfn-for` with the HTML `sizes` attribute name, and I am still unsure of what a `value` is, because it says that there is only `value` and `descriptor` that can have `data-dfn-for`, ie. `type`, which are annotated in `<>` cannot be namespaced.

**Comment by tidoust** [comment]
Hmm, where does the documentation say that "there is only value and descriptor that can have data-dfn-for"?

The [Namespacing a definition](https://tabatkins.github.io/bikeshed/#dfn-for) section makes the attribute mandatory for a number of definition types but does not prevent other types from being namespaced too. In practice, while most `type` and `function` definitions are not namespaced, some are and have a `data-dfn-for` attribute (there are two ["child" selectors](https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo) too). Whether all of this is intentional is, as usual, a good question ;)

I wouldn't add `data-dfn-for` attributes to the HTML definitions here, especially if you want them to appear in the extract: `sizes` is a construct of type `element-attr`, and CSS extracts do not contain these constructs for now, so crawler wouldn't be able to attach these types anywhere.

**Comment by cdoublev** [comment]
Yeah, good points, this is allowed.

You are also right for `sizes`. `data-dfn-for` is not intended to namespace a CSS value with an HTML attribute. I was just checking.
