### ISSUE TITLE
How are spec redirects handled?

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/reffy#1236]
Recently, `resource-hints` started to redirect to HTML spec (https://github.com/w3c/resource-hints/commit/a2d8f5a65c6174fd96c68f0e876c10ee32b97482).
Since then, `Window` is defined in HTML as well as resource-hints in Webref data (see [ReSpec xref API response](https://user-images.githubusercontent.com/8426945/226100926-45df6c5d-ec0c-477a-954f-c39c2ab5ff18.png)).
You can see in https://github.com/w3c/webref/commit/4a5b4cf79c8042b6283f07780dc181c8029da85d, there's large update in data from resource-hints.
This ambiguity is presently [breaking some tests in ReSpec](https://github.com/w3c/respec/actions/runs/4446203038/jobs/7824440625#step:6:241) (and likely some specs that use ReSpec).

**Comment by sidvishnoi** [comment]
I did some reading, and apparently we've to add resource hints to [browser-specs ignore list](https://github.com/w3c/browser-specs/blob/main/src/data/ignore.json)?

**Comment by tidoust** [comment]
Yes, I didn't have time to do that before I left for a few days off last week, and hadn't anticipated that this would import HTML dfns into Resource Hints... Needed steps should be:
1. Remove Resource Hints from browser-specs's `specs.json` file.
2. Add an entry to browser-spec's `ignore.json` file (just need to avoid the spec being proposed again by the job that looks for new specs).
3. Publish a new version of web-specs
4. Integrate the new version of web-specs into Reffy
5. Publish a new version of Reffy

@dontcallmedom, I did 1. and 2. Cannot do 3. for now as pre-release action crashed due to an internal GitHub API error. I'll be afk in the next few hours. Could you take care of it?

**Comment by dontcallmedom** [comment]
I think it should now be all fixed, with resource-hints now gone from webref
