### ISSUE TITLE
Reffy is exporting non-exported terms?

### ISSUE THREAD

**Issue by fantasai** [w3c/reffy#1250]
Using [=ascii case-insensitive=] should link over to Infra, but Bikeshed is reporting that it conflicts with WebCryptoAPI. However, I can't find any markup in the WebCryptoAPI spec that would indicate that their ascii case-insensitive DFN should be exported.

Can you fix Reffy so that only exported terms get exported, or explain why reffy thinks this DFN should be exported so that WebCryptoAPI can stop exporting it?

Thanks~

**Comment by tidoust** [comment]
The WebCrypto API is old enough that it does not follow the usual dfn data model. Reffy considers that definitions in old specs are exported by default. That is useful in a number of other cases.

We are considering curating definitions (tracked in https://github.com/w3c/webref/issues/789) but curation involves manual intervention and, for definitions, we need to find a balance between being up-to-date and producing results without ambiguity, as we cannot commit to maintaining patches on a daily basis.

Different specs do export definitions that are already defined elsewhere in practice, see e.g. https://github.com/w3c/webref/issues/306#issuecomment-1354716857 (not sure why WebCrypto does not appear in that list though). In other words, we're not yet at a point where we have a clean global namespace for definitions. That isn't an issue with Respec specs because authors need to be explicit about the list of specs to use for xref purpose. Bikeshed does not have such a mechanism.

I'll look into patching Reffy to make an exception for WebCrypto. Looking at references across specs, there are a number of references to WebCrypto that indeed need fixing:

- In Turtledove, [ref to Throw](https://wicg.github.io/turtledove/#ref-for-concept-throw)
- In IndexedDB 3.0, [ref to Type](https://w3c.github.io/IndexedDB/#ref-for-dfn-CryptoKey-slot-type)
- In Capability Detection, [ref to DOMException](https://wicg.github.io/capability-delegation/spec.html#ref-for-dfn-DOMException)
- In WebDriver Bidi, [ref to TypeError](https://w3c.github.io/webdriver-bidi/#ref-for-dfn-TypeError)
- In CSS Animations 1, [ref to case-sensitive](https://drafts.csswg.org/css-animations-1/#ref-for-case-sensitive)

There remain a few references to WebCrypto that seem correct:

- WebRTC, refs to `AlgorithmIdentifier`
- WebRTC Encoded Transforms, [ref to `CryptoKey`](https://w3c.github.io/webrtc-encoded-transform/#ref-for-dfn-CryptoKey)
- WebCrypto Secure Curves, refs in [Conventions](https://wicg.github.io/webcrypto-secure-curves/#specification-conventions)
- HTML, [ref to generate a random UUID](https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate)
- Prerendering revamped, [ref to generate a random UUID](https://wicg.github.io/nav-speculation/prerendering.html#ref-for-dfn-generate-a-random-uuid)

**Comment by tidoust** [comment]
Going a bit deeper into details, the problem is really the /TR version of the spec. The [nightly version](https://w3c.github.io/webcrypto/) of the spec follows the right dfn data model and only export definitions that need to be.

In practice, the references to WebCrypto either are to concepts only defined in the nightly version ("generate a random UUID") or are made through explicit links (through `<a data-cite="...">`) and thus do not rely on xref data. In other words, I think that we can safely force the definitions in the /TR version of WebCrypto to be "non-exported".

**Comment by tidoust** [comment]
Crawler was patched not to export definitions from the release version of the WebCrypto API. Most of the specs mentioned above that incorrectly linked to WebCrypto have been re-generated since last week and no longer link to WebCrypto as a result. I created pull requests to fix remaining specs: https://github.com/w3c/IndexedDB/pull/401 and https://github.com/WICG/capability-delegation/pull/35
