### ISSUE TITLE
Use a single browser instance

### ISSUE THREAD

**Issue by gsnedders** [w3c/reffy#415]
Running locally, it appears the runtime of crawls is dominated by starting/restarting Chromium. Making it possible to run with a single instance should be a pretty big perf win.

**Comment by tidoust** [comment]
That's worth a try.

I erred on the safe side, restarting from scratch for every spec as I vaguely recall discussions with @foolip that using multiple tabs of the same instance of the headless browser returned by Puppeteer could introduce weird issues such as out of memory errors. I didn't really try that out though. Plus we wouldn't be creating hundreds of tabs at once in any case. Well, and that was some time ago, lots of bugs have been fixed in Puppeteer since then.

**Comment by gsnedders** [comment]
I wonder if even just doing it sequentially within a single tab would be quicker than all the restarting?

**Comment by gsnedders** [comment]
The other thing that comes to mind is "what if you send the built reffy over Puppetter and just return the result object from Puppeteer", rather than iterating over large numbers of elements in node (and hence having lots of IPC to/from the content process to node).

**Comment by tidoust** [comment]
> I wonder if even just doing it sequentially within a single tab would be quicker than all the restarting?

Some specs take a long time to process (e.g. the HTML spec, or the SVG spec because the code needs to fetch pages one by one), so having a handful of specs processed in parallel is likely going to remain useful. The crawl currently processes 4 specs in parallel. But 4 tabs remain fairly reasonable.


> The other thing that comes to mind is "what if you send the built reffy over Puppetter and just return the result object from Puppeteer", rather than iterating over large numbers of elements in node (and hence having lots of IPC to/from the content process to node).

Yes. The code is more the result of an evolution (we were using JSDOM before the switch to Puppeteer) than of a carefully crafted architecture, and we haven't really paid attention to crawling performances until now. If crawling performances are important, then running the entire code in Puppeteer land also seems like a good thing to do.

This may make debugging even harder than it is today though... or perhaps not, it's easy to switch the `headless` setting to `false`, which effectively gives access to dev tools for the code that runs in the browser.

**Comment by foolip** [comment]
Using the same browser instance but a new page for every spec should isolate things well enough and avoid much of the overhead.

**Comment by tidoust** [comment]
> Running locally, it appears the runtime of crawls is dominated by starting/restarting Chromium

Digging into this, I note I don't really see a "domination". On my machine, instrumenting the `processSpecification` function shows that starting/closing Puppeteer takes about 150ms each. That's not unsignificant, but that's to be compared with the actual loading and processing of the page, which takes 2-4s on typical specs. Did I miss something? Do you get other results?
