### ISSUE TITLE
Interfaces from WebCryptoAPI are exported as dfn

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/reffy#563]
See https://www.w3.org/TR/WebCryptoAPI/#dfn-Crypto 
Webref data: https://github.com/w3c/webref/blob/417873681b8fbdebc19b0542ba5a243e29bf490e/tr/dfns/WebCryptoAPI.json#L420-L436

The spec uses `pre.code > code.idl-code` to declare IDL blocks, so I think it should've been extracted as IDL using: https://github.com/w3c/reffy/blob/76b1737eef1219b43002ffd67be8c556db426375/src/browserlib/extract-webidl.mjs#L108

Came across this when using webref/xref data in https://wicg.github.io/uuid/.

**Comment by tidoust** [comment]
The problem is that, since this document was published 4 years ago, it does not fully respect the [Definitions data model](https://tabatkins.github.io/bikeshed/#dfn-contract). The definition should have a `data-dfn-type` set to `interface` in particular.

The Editor's Draft does not have this problem:
https://github.com/w3c/webref/blob/417873681b8fbdebc19b0542ba5a243e29bf490e/ed/dfns/WebCryptoAPI.json#L341

I thought ReSpec was using ED data and not TR data for xref. When and how do you use TR dfns?

PS: There's another issue with the definition in the ED though. The actual [Crypto definition](https://w3c.github.io/webcrypto/#dfn-Crypto) is in a section marked as non-normative, and thus Reffy considers that it is informative. I filed https://github.com/w3c/webcrypto/issues/252

**Comment by sidvishnoi** [comment]
> The definition should have a data-dfn-type set to interface in particular.

Ah, right. I was looking for definition  via IDL parsing instead of `<dfn>`. 🤦‍♂️
This resolves the issue. 

> I thought ReSpec was using ED data and not TR data for xref. When and how do you use TR dfns?

Currently it uses ED data, but there's an open issue to allow both TR/ED as needed: https://github.com/w3c/respec/issues/3246

---

Thanks for filing w3c/webcrypto#252!
