### ISSUE TITLE
Definitions should be verified to have a valid dfn type

### ISSUE THREAD

**Issue by tabatkins** [w3c/reffy#658]
While reviewing the effects of switching Bikeshed's dfn harvester to Reffy, I noticed a new dfn cropped in with a type of "idl" <https://github.com/w3c/webref/blob/master/tr/dfns/payment-request.json#L1992>

This isn't a valid [definition type](https://tabatkins.github.io/bikeshed/#dfn-types). (It's a [linking supertype](https://tabatkins.github.io/bikeshed/#link-types) that encompasses all the IDL-related types.)

I guess the type of a dfn should be verified to be valid, and the dfn omitted if it's not?

(I [reported this on ReSpec as well](https://github.com/w3c/respec/issues/3644), since it's not being reported as an error in the source document, but regardless of the inputs, the Reffy data should be clean.)

**Comment by tabatkins** [comment]
(All the currently-recognized dfn types are at <https://github.com/tabatkins/bikeshed/blob/main/bikeshed/config/dfnTypes.py#L4>, + "dfn".)

**Comment by tidoust** [comment]
Looking at dfn types that are currently extracted, "idl" seems to be the only incorrect type in specs for the time being.

There are also "event" and "namespace" types that are not in the documentation but since they are in [dfnTypes.py](https://github.com/tabatkins/bikeshed/blob/main/bikeshed/config/dfnTypes.py#L4), this seems more a doc maintenance issue.
