### ISSUE TITLE
CSS terminal values extracted as non-terminals

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#971]
For example, `annotation(<feature-value-name>)` is extracted as `"<annotation()>": { "value": "annotation(<feature-value-name>)" }` from [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#annotation) but `<annotation()>` does not appear in any value definition.

`annotation(<feature-value-name>)` is marked up with `data-dfn-type="value"` and according to https://github.com/w3c/csswg-drafts/issues/7380#issuecomment-1159125937, it should be treated the same as a keyword:

> While our functions are often uniquely named, they should in fact be treated the same as keywords - potentially context-sensitive.

I think it should be extracted as `"annotation(<feature-value-name>)": { "prose": "Enables display of alternate annotation forms (font specific, OpenType feature: nalt <feature-index>)" }` or just ignored (like keywords).

Note that some non-terminals looks like function, eg. `<calc()>`, and some terminals are annoted between angled brackets, eg. `<number>`. [`<image-set()>`](https://drafts.csswg.org/css-images-4/#funcdef-image-set) is an example of a function definition (with `data-dfn-type="function"`) referenced as a production ([terminal - CSS basic data type - or non-terminal wrapped between `<` and `>`](https://drafts.csswg.org/css-values-4/#component-types)) from another definition, [`<image>`](https://drafts.csswg.org/css-images-4/#typedef-image):

> `<image> = <url> | <image()> | <image-set()> | <cross-fade()> | <element()> | <gradient>`

Note that in its definition, `<image-set()>` is not wrapped between `<` and `>`, which may seem confusing...:

> `image-set() = image-set( <image-set-option># )`

...whereas eg. `<calc()>` is defined with `data-link-type="function"` as:

> `<calc()>  = calc( <calc-sum> )`

**Comment by tidoust** [comment]
Yes, we could look into `data-dfn-type` to create entries that go into `valuespaces`, and e.g. only consider the ones defined with a `data-dfn-type="function"`. That would provide more consistent results with fewer dangling values, even though we would miss a number of entries that are currently defined as `value` whereas it seems to me that they should rather be `function`. Typically, I would expect to see `annotation()` defined as `function`, and referenced through `<annotation()>` from the definition of `font-variant-alternates` so as to be able to create a link between to the definition of `annotation`, as done in some other CSS specs.

Are dangling values problematic though? If the goal is to get rid of dangling values from the extracts, we could also just loop through values during data curation and drop them. There are a bunch of dangling values that exist because they get referenced from prose, and thus don't appear in any value definition.

On top of looking at `data-dfn-type`, what seems more important to me is to save the `data-dfn-for` attribute in the CSS extracts. That would provide the contextual flag I was alluding to in https://github.com/w3c/webref/issues/127#issuecomment-1098022559:

> From a CSS extract perspective, we should rather find a way to flag the rect() definition in CSS Masking, e.g. as only applying locally.

That would also allow us to extract terminal values along with a bit of prose. Terminal values are much more likely to have contextual definitions (e.g. `auto` or `none`).

**Comment by cdoublev** [comment]
Keeping functions defined with `data-dfn-for="value"` in `valuespaces` is not really a problem to me. It would make sense to also have keywords (eg. `auto` or `none`) and to associate their contextual definition (prose and `data-dfn-for`).

Personally, I would ignore them when generating a productions (defined with `type` or `function` as the value for `data-fn-type`) record since they are useless for parsing a CSS input. Those that are currently associated to a `value` are errors (`selector()`, `layout()`, etc.).

Referencing them in `valuspaces` as productions, ie. with their name between `<` and `>`, would make this task a little more difficult but more importantly it seems inappropriate. From https://github.com/w3c/fxtf-drafts/issues/411#issuecomment-1159148605:

> Naming conflicts in productions are not allowed, but they do show up. Happy to fix them when they're pointed out.

That means that productions must be defined once.

I believe there is no example of a function defined with `data-dfn-for="value"` that is used with different value definitions.

`fit-content()` is defined in CSS Grid and CSS Sizing with different *semantic* definitions.

`annotation()`, which is currently only used as `annotation(<feature-value-name>)` in the value definition of the `font-variant-alternates` property, could for example be set with `annotation(<number>)` in the value definition of another property or a production, associated to its own contextual definition, and possibly to specific parsing or serialization rules.

**Comment by tidoust** [comment]
Extraction rules have now been adjusted in Reffy, and released in [`@webref/css` v4.3.0](https://www.npmjs.com/package/@webref/css/v/4.3.0).

Taking `data-dfn-for` attributes into account would allow us to drop remaining cases that are currently handled in Webref as exceptions-to-the-rules to get back to only one definition. Follow-up issue in #980.

**Comment by cdoublev** [comment]
Thank you for this update. I guess it must be super fun to parse the contents of these specs.

I can not figure out how [`<layout()>`](https://github.com/w3c/webref/blob/47a016a7481688e9625001207b1713ea7812a159/ed/css/css-layout-api.json#L9), which is marked up with `data-dfn-type="value"`, is still extracted from CSS Layout API, from reading the code for the `extract-cssdfn` module.

**Comment by tidoust** [comment]
> I can not figure out how [`<layout()>`](https://github.com/w3c/webref/blob/47a016a7481688e9625001207b1713ea7812a159/ed/css/css-layout-api.json#L9), which is marked up with `data-dfn-type="value"`, is still extracted from CSS Layout API, from reading the code for the `extract-cssdfn` module.

It is no longer extracted but since that's the only thing that was extracted from the spec, removing it means removing the extract, and we don't remove extracts automatically from webref (this is done on purpose to keep extracts around when there is a transient error that makes it impossible to crawl a spec on a temporary basis). We review dangling extracts once per week. I just did it in #649 and dropped the offending extract.

**Comment by cdoublev** [comment]
[Got it](https://github.com/w3c/webref/pull/649), thanks.
